name: zeroae-rocksdb-dev
channels:
  - zeroae
  - conda-forge
  - defaults
dependencies:
  - python
  - pip

  # Build Requirements
  - compilers
  - swig >=4

  # Setup Requirements (setup.py:setup_requirements)
  - pytest-runner >=5
  - rocksdb
  - setuptools_scm
  - wheel

  # Install Requirements (setup.py:requirements)
  - click >=7.0
  - click-plugins
  - entrypoints

  # Test Requirements (setup.py:test_requirements)
  - pytest >=3
  - pytest-cov

  # Documentation Requirements
  - sphinx
  - watchdog

  # Dev Workflow requirements
  - jupyter
  - pre-commit
  - black
  - flake8
  - twine

